### ISSUE TITLE
Roadmap and updates

### ISSUE THREAD

**Issue by hex22a** [bulatei/node-selectel-storage#2]
Selectel storge api has been updated.

То есть Селектела обновились апи 
https://blog.selectel.ru/oblachnoe-xranilishe-novye-funkcji-api/
Будем обновлять?

**Comment by hex22a** [comment]
Алсо было бы круто сделать загрузку файла не только с диска
Могу сам заняться ты только окни и жди пулл реквеста

**Comment by bulatei** [comment]
Да, обновим, как время будет. еще старое не дописан, то что мне нужно было реализовал и забросил, если добавите жду пулл реквеста.

**Comment by bulatei** [comment]
что вы имеете ввиду "не только с диска". предлагайте

**Comment by hex22a** [comment]
selectel.uploadFile('fullLocalPath'......

там внутри у вас fs читает файл. можно было бы добавить историю когда мы передаем не путь к файлу а сам файл (например если он пришел нам из запроса на какой-нибудь сервер а писать на свой диск мы не хотим)

**Comment by bulatei** [comment]
понял, как ретранслятор(или как он там еще называется). это я реализовывал, забыл видимо закинуть. найду закину, не найду напишу закину.
